---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dockercoins
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/dockercoins/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: dockercoins
---
kind: Namespace
apiVersion: v1
metadata:
  name: dockercoins
